//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.SampleDataSource
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class SampleDataSource { }
#else

	public class SampleDataSource : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public SampleDataSource()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/GoogleReader;component/SampleData/SampleDataSource/SampleDataSource.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private ItemCollection _Collection = new ItemCollection();

		public ItemCollection Collection
		{
			get
			{
				return this._Collection;
			}
		}
	}

	public class Item : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _Title_text = string.Empty;

		public string Title_text
		{
			get
			{
				return this._Title_text;
			}

			set
			{
				if (this._Title_text != value)
				{
					this._Title_text = value;
					this.OnPropertyChanged("Title_text");
				}
			}
		}

		private string _Feed_name = string.Empty;

		public string Feed_name
		{
			get
			{
				return this._Feed_name;
			}

			set
			{
				if (this._Feed_name != value)
				{
					this._Feed_name = value;
					this.OnPropertyChanged("Feed_name");
				}
			}
		}

		private System.Windows.Media.ImageSource _Item_Image = null;

		public System.Windows.Media.ImageSource Item_Image
		{
			get
			{
				return this._Item_Image;
			}

			set
			{
				if (this._Item_Image != value)
				{
					this._Item_Image = value;
					this.OnPropertyChanged("Item_Image");
				}
			}
		}
	}

	public class ItemCollection : System.Collections.ObjectModel.ObservableCollection<Item>
	{ 
	}
#endif
}
